[graph]
exclude-dev = true

[advisories]
unmaintained = "all"
yanked = "warn"

[bans]
multiple-versions = "warn"
wildcards = "warn"
deny = ["*"]

[licenses]
allow = ["MIT", "Apache-2.0"]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
