[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"

[bans]
multiple-versions = "warn"
wildcards = "warn"

# Deny all dependencies
[dependencies]
allow-build = []
deny = ["*"]

# Allow dev-dependencies (e.g. for docs, examples)
[dev-dependencies]
allow = ["*"]
